/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR(100), 
    date_of_birth DATE, 
    escape_attempts INTEGER, 
    neutered BOOLEAN, 
    weight_kg DECIMAL,
    species VARCHAR(100)
);

CREATE TABLE owners (
 id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 full_name VARCHAR(200),
 age INT
);

CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
);

-- -- Alter table 

-- Animal
ALTER TABLE animals 
DROP COLUMN species,
ADD COLUMN species_id INTEGER REFERENCES species(id),
ADD COLUMN owner_id INTEGER REFERENCES owners(id);

-- Add an email column - owners table
ALTER TABLE owners ADD COLUMN email VARCHAR(120);

-- Change name of column on table visits
alter table visits RENAME COLUMN visit_date TO date_of_visit;


-- JOIN TABLES

CREATE TABLE vets (
    id SERIAL PRIMARY KEY,
    name VARCHAR(150),
    age INT,
    date_of_graduation DATE
);

CREATE TABLE specializations(
    specie_id INT REFERENCES species(id),
    vet_id INT REFERENCES vets(id)
);

CREATE TABLE visits(
    animal_id INT REFERENCES animals(id),
    vet_id INT REFERENCES vets(id),
    visit_date DATE,
);

-- indexes CREATE
BEGIN;
CREATE INDEX animal_id_asc ON visits(animal_id ASC);
COMMIT;